name: ✨ Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["enhancement", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please describe what you'd like to see.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve?
      placeholder: I'm frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the feature you'd like
      placeholder: I would like...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Any alternative solutions you've considered?
      placeholder: I've also thought about...

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which component would this affect?
      options:
        - oni_bitcoin (primitives/encodings)
        - oni_consensus (script/validation)
        - oni_storage (chainstate/DB)
        - oni_p2p (networking)
        - oni_rpc (RPC server)
        - oni_node (OTP app)
        - Build/CI/Tooling
        - Documentation
        - New component
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature?
      options:
        - Nice to have
        - Would significantly improve experience
        - Critical for my use case
    validations:
      required: true

  - type: checkboxes
    id: consensus
    attributes:
      label: Consensus Considerations
      description: Does this feature affect consensus?
      options:
        - label: This feature requires consensus code changes
        - label: This feature implements a BIP (specify in additional context)

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      options:
        - label: I'm willing to help implement this feature
        - label: I can provide test cases or test vectors

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, mockups, or examples
